site_name: FoxAngol
site_description: Angoltanulás, kommunikáció és nyelvi önbizalom
site_url: https://foxangol.netlify.app/

theme:
  name: material
  language: hu

nav:
  - Főoldal: index.md
  - Rólam: about.md
  - Óratípusok: oratipusok.md
  - Rólam írták: rolam-irtak.md
  - Blog:
      - Áttekintés: blog/index.md
      - Idősen is bele lehet fogni a nyelvtanulásba: blog/posts/idosen-is-bele-lehet-fogni-a-nyelvtanulasba.md
      - Miben segít, ha idegen nyelven olvasol: blog/posts/miben-segit.md