site_name: FoxAngol
site_description: Angoltanulás, kommunikáció és nyelvi önbizalom
site_url: https://foxangol.netlify.app/

theme:
  name: material
  language: hu

nav:
  - Főoldal: index.md
  - Rólam: about.md
  - Kapcsolat: kapcsolat.md
  - Óratípusok: oratipusok.md
  - Rólam írták: rolam-irtak.md
  - Blog:
      - Áttekintés: blog/index.md
      - Idősen is bele lehet fogni a nyelvtanulásba: blog/posts/idosen-is-bele-lehet-fogni-a-nyelvtanulasba.md
      - Miben segít, ha idegen nyelven olvasol: blog/posts/miben-segit.md
      - Az 's használata: blog/posts/aposztrof.md
      - Miért válaszd az IELTS nyelvvizsgát?: blog/posts/ielts.md
      - Interjú Kovács Gabriellával: blog/posts/kovacs-gabi-interju.md
      - A gyakoriságot kifejező időhatározók (Adverbs of Frequency) és helyük a mondatban: adverbs-of-frequency.md